// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ViewInitParameters struct {

	// (String) Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
	// Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// (String) View name.
	// View name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Explorer the view belongs to: logs or traces.
	// Explorer the view belongs to: `logs` or `traces`.
	SourcePage *string `json:"sourcePage,omitempty" tf:"source_page,omitempty"`
}

type ViewObservation struct {

	// (String) Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
	// Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// assigned view id.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) View name.
	// View name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Explorer the view belongs to: logs or traces.
	// Explorer the view belongs to: `logs` or `traces`.
	SourcePage *string `json:"sourcePage,omitempty" tf:"source_page,omitempty"`
}

type ViewParameters struct {

	// (String) Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
	// Saved query state as JSON (compositeQuery, filters, columns, …). Compared semantically.
	// +kubebuilder:validation:Optional
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// (String) View name.
	// View name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Explorer the view belongs to: logs or traces.
	// Explorer the view belongs to: `logs` or `traces`.
	// +kubebuilder:validation:Optional
	SourcePage *string `json:"sourcePage,omitempty" tf:"source_page,omitempty"`
}

// ViewSpec defines the desired state of View
type ViewSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ViewParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ViewInitParameters `json:"initProvider,omitempty"`
}

// ViewStatus defines the observed state of View.
type ViewStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ViewObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// View is the Schema for the Views API. A saved SigNoz explorer view (logs or traces). The query state goes in data as JSON.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,signoz}
type View struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.data) || (has(self.initProvider) && has(self.initProvider.data))",message="spec.forProvider.data is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sourcePage) || (has(self.initProvider) && has(self.initProvider.sourcePage))",message="spec.forProvider.sourcePage is a required parameter"
	Spec   ViewSpec   `json:"spec"`
	Status ViewStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ViewList contains a list of Views
type ViewList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []View `json:"items"`
}

// Repository type metadata.
var (
	View_Kind             = "View"
	View_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: View_Kind}.String()
	View_KindAPIVersion   = View_Kind + "." + CRDGroupVersion.String()
	View_GroupVersionKind = CRDGroupVersion.WithKind(View_Kind)
)

func init() {
	SchemeBuilder.Register(&View{}, &ViewList{})
}
