// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AlertInitParameters struct {

	// (String) Alert name.
	// Alert name.
	Alert *string `json:"alert,omitempty" tf:"alert,omitempty"`

	// (String) One of METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, EXCEPTIONS_BASED_ALERT.
	// One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
	AlertType *string `json:"alertType,omitempty" tf:"alert_type,omitempty"`

	// (String) Query condition as JSON (compositeQuery + thresholds). Compared semantically.
	// Query condition as JSON (compositeQuery + thresholds). Compared semantically.
	Condition *string `json:"condition,omitempty" tf:"condition,omitempty"`

	// readable description.
	// Human-readable description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the rule is disabled. Defaults to false.
	// Whether the rule is disabled. Defaults to false.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) Evaluation window (e.g. 5m0s).
	// Evaluation window (e.g. `5m0s`).
	EvalWindow *string `json:"evalWindow,omitempty" tf:"eval_window,omitempty"`

	// (String) Evaluation block as JSON (v2alpha1+). Compared semantically.
	// Evaluation block as JSON (v2alpha1+). Compared semantically.
	Evaluation *string `json:"evaluation,omitempty" tf:"evaluation,omitempty"`

	// (String) Evaluation frequency (e.g. 1m0s).
	// Evaluation frequency (e.g. `1m0s`).
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (Map of String) Custom labels attached to the alert.
	// Custom labels attached to the alert.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Notification settings as JSON (renotify, group_by, use_policy). Compared semantically.
	// Notification settings as JSON (renotify, group_by, use_policy). Compared semantically.
	NotificationSettings *string `json:"notificationSettings,omitempty" tf:"notification_settings,omitempty"`

	// (List of String) Notification channel names the alert routes to.
	// Notification channel names the alert routes to.
	PreferredChannels []*string `json:"preferredChannels,omitempty" tf:"preferred_channels,omitempty"`

	// (String) Rule engine type: threshold_rule (default) or promql_rule.
	// Rule engine type: `threshold_rule` (default) or `promql_rule`.
	RuleType *string `json:"ruleType,omitempty" tf:"rule_type,omitempty"`

	// (String) Alert schema version. Defaults to v2alpha1.
	// Alert schema version. Defaults to `v2alpha1`.
	SchemaVersion *string `json:"schemaVersion,omitempty" tf:"schema_version,omitempty"`

	// (String) Severity label (e.g. info, warning, critical).
	// Severity label (e.g. `info`, `warning`, `critical`).
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// (String) Source URL recorded on the rule.
	// Source URL recorded on the rule.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) Alert API version. Defaults to v5 .
	// Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type AlertObservation struct {

	// (String) Alert name.
	// Alert name.
	Alert *string `json:"alert,omitempty" tf:"alert,omitempty"`

	// (String) One of METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, EXCEPTIONS_BASED_ALERT.
	// One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
	AlertType *string `json:"alertType,omitempty" tf:"alert_type,omitempty"`

	// (String) Query condition as JSON (compositeQuery + thresholds). Compared semantically.
	// Query condition as JSON (compositeQuery + thresholds). Compared semantically.
	Condition *string `json:"condition,omitempty" tf:"condition,omitempty"`

	// readable description.
	// Human-readable description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the rule is disabled. Defaults to false.
	// Whether the rule is disabled. Defaults to false.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) Evaluation window (e.g. 5m0s).
	// Evaluation window (e.g. `5m0s`).
	EvalWindow *string `json:"evalWindow,omitempty" tf:"eval_window,omitempty"`

	// (String) Evaluation block as JSON (v2alpha1+). Compared semantically.
	// Evaluation block as JSON (v2alpha1+). Compared semantically.
	Evaluation *string `json:"evaluation,omitempty" tf:"evaluation,omitempty"`

	// (String) Evaluation frequency (e.g. 1m0s).
	// Evaluation frequency (e.g. `1m0s`).
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// assigned alert rule id.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String) Custom labels attached to the alert.
	// Custom labels attached to the alert.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Notification settings as JSON (renotify, group_by, use_policy). Compared semantically.
	// Notification settings as JSON (renotify, group_by, use_policy). Compared semantically.
	NotificationSettings *string `json:"notificationSettings,omitempty" tf:"notification_settings,omitempty"`

	// (List of String) Notification channel names the alert routes to.
	// Notification channel names the alert routes to.
	PreferredChannels []*string `json:"preferredChannels,omitempty" tf:"preferred_channels,omitempty"`

	// (String) Rule engine type: threshold_rule (default) or promql_rule.
	// Rule engine type: `threshold_rule` (default) or `promql_rule`.
	RuleType *string `json:"ruleType,omitempty" tf:"rule_type,omitempty"`

	// (String) Alert schema version. Defaults to v2alpha1.
	// Alert schema version. Defaults to `v2alpha1`.
	SchemaVersion *string `json:"schemaVersion,omitempty" tf:"schema_version,omitempty"`

	// (String) Severity label (e.g. info, warning, critical).
	// Severity label (e.g. `info`, `warning`, `critical`).
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// (String) Source URL recorded on the rule.
	// Source URL recorded on the rule.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) Alert API version. Defaults to v5 .
	// Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type AlertParameters struct {

	// (String) Alert name.
	// Alert name.
	// +kubebuilder:validation:Optional
	Alert *string `json:"alert,omitempty" tf:"alert,omitempty"`

	// (String) One of METRIC_BASED_ALERT, LOGS_BASED_ALERT, TRACES_BASED_ALERT, EXCEPTIONS_BASED_ALERT.
	// One of `METRIC_BASED_ALERT`, `LOGS_BASED_ALERT`, `TRACES_BASED_ALERT`, `EXCEPTIONS_BASED_ALERT`.
	// +kubebuilder:validation:Optional
	AlertType *string `json:"alertType,omitempty" tf:"alert_type,omitempty"`

	// (String) Query condition as JSON (compositeQuery + thresholds). Compared semantically.
	// Query condition as JSON (compositeQuery + thresholds). Compared semantically.
	// +kubebuilder:validation:Optional
	Condition *string `json:"condition,omitempty" tf:"condition,omitempty"`

	// readable description.
	// Human-readable description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the rule is disabled. Defaults to false.
	// Whether the rule is disabled. Defaults to false.
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) Evaluation window (e.g. 5m0s).
	// Evaluation window (e.g. `5m0s`).
	// +kubebuilder:validation:Optional
	EvalWindow *string `json:"evalWindow,omitempty" tf:"eval_window,omitempty"`

	// (String) Evaluation block as JSON (v2alpha1+). Compared semantically.
	// Evaluation block as JSON (v2alpha1+). Compared semantically.
	// +kubebuilder:validation:Optional
	Evaluation *string `json:"evaluation,omitempty" tf:"evaluation,omitempty"`

	// (String) Evaluation frequency (e.g. 1m0s).
	// Evaluation frequency (e.g. `1m0s`).
	// +kubebuilder:validation:Optional
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (Map of String) Custom labels attached to the alert.
	// Custom labels attached to the alert.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Notification settings as JSON (renotify, group_by, use_policy). Compared semantically.
	// Notification settings as JSON (renotify, group_by, use_policy). Compared semantically.
	// +kubebuilder:validation:Optional
	NotificationSettings *string `json:"notificationSettings,omitempty" tf:"notification_settings,omitempty"`

	// (List of String) Notification channel names the alert routes to.
	// Notification channel names the alert routes to.
	// +kubebuilder:validation:Optional
	PreferredChannels []*string `json:"preferredChannels,omitempty" tf:"preferred_channels,omitempty"`

	// (String) Rule engine type: threshold_rule (default) or promql_rule.
	// Rule engine type: `threshold_rule` (default) or `promql_rule`.
	// +kubebuilder:validation:Optional
	RuleType *string `json:"ruleType,omitempty" tf:"rule_type,omitempty"`

	// (String) Alert schema version. Defaults to v2alpha1.
	// Alert schema version. Defaults to `v2alpha1`.
	// +kubebuilder:validation:Optional
	SchemaVersion *string `json:"schemaVersion,omitempty" tf:"schema_version,omitempty"`

	// (String) Severity label (e.g. info, warning, critical).
	// Severity label (e.g. `info`, `warning`, `critical`).
	// +kubebuilder:validation:Optional
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// (String) Source URL recorded on the rule.
	// Source URL recorded on the rule.
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) Alert API version. Defaults to v5 .
	// Alert API version. Defaults to `v5` (required by SigNoz >= 0.125).
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

// AlertSpec defines the desired state of Alert
type AlertSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AlertParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AlertInitParameters `json:"initProvider,omitempty"`
}

// AlertStatus defines the observed state of Alert.
type AlertStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AlertObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Alert is the Schema for the Alerts API. A SigNoz alert rule. Top-level fields are typed; the query condition, evaluation, and notification_settings are JSON blobs (export from the SigNoz UI to adapt). Defaults target the v5 / v2alpha1 schema required by SigNoz >= 0.125.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,signoz}
type Alert struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.alert) || (has(self.initProvider) && has(self.initProvider.alert))",message="spec.forProvider.alert is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.alertType) || (has(self.initProvider) && has(self.initProvider.alertType))",message="spec.forProvider.alertType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.condition) || (has(self.initProvider) && has(self.initProvider.condition))",message="spec.forProvider.condition is a required parameter"
	Spec   AlertSpec   `json:"spec"`
	Status AlertStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AlertList contains a list of Alerts
type AlertList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Alert `json:"items"`
}

// Repository type metadata.
var (
	Alert_Kind             = "Alert"
	Alert_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Alert_Kind}.String()
	Alert_KindAPIVersion   = Alert_Kind + "." + CRDGroupVersion.String()
	Alert_GroupVersionKind = CRDGroupVersion.WithKind(Alert_Kind)
)

func init() {
	SchemeBuilder.Register(&Alert{}, &AlertList{})
}
