apiVersion: saved.signoz.crossplane.io/v1alpha1
kind: View
metadata:
  annotations:
    meta.upbound.io/example-id: saved/v1alpha1/view
  labels:
    testing.upbound.io/example-name: errors
  name: errors
spec:
  forProvider:
    data: |-
      ${jsonencode({
          compositeQuery = {
            queryType = "builder"
            panelType = "list"
            builderQueries = {
              A = {
                dataSource        = "logs"
                queryName         = "A"
                aggregateOperator = "noop"
                expression        = "A"
                disabled          = false
              }
            }
          }
        })}
    name: Errors (last 15m)
    sourcePage: logs
